In [ ]:
import pandas as pd
df = pd.read_csv('optimized_dataset2.csv')
df

encoded_3   encoded_4    encoded_5  encoded_6   encoded_9  encoded_10  \
0      0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   
1      0.000000  1315.50320     0.000000    0.00000    0.000000     0.00000   
2   1502.516100     0.00000     0.000000    0.00000    0.000000     0.00000   
3      0.000000     0.00000   256.931920    0.00000  146.509100     0.00000   
4      0.000000     0.00000     0.000000    0.00000  202.074480   148.24594   
5      0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   
6    594.314300     0.00000    62.417095    0.00000    0.000000    97.16145   
7      0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   
8      9.514465     0.00000  1332.419200  663.35657    0.000000     0.00000   
9     91.228584   718.65936    27.713186  163.79999  128.901960     0.00000   
10     0.000000     0.00000     0.000000  997.79640    0.000000  1466.65970   
11     0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   
12     0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   
13    29.602976     0.00000   158.716220  340.45935  316.091400   161.70341   
14     0.000000   579.78076   128.279430  347.70718  452.851320     0.00000   
15    14.473581     0.00000   104.224070    0.00000  223.199920   291.86676   
16     0.000000     0.00000     0.000000    0.00000   59.178630     0.00000   
17     0.000000     0.00000     0.000000    0.00000   59.001114     0.00000   
18     0.000000     0.00000     0.000000    0.00000   50.369534     0.00000   
19     0.000000     0.00000     0.000000    0.00000   60.103855     0.00000   
20     0.000000     0.00000     0.000000    0.00000    0.000000     0.00000   

    encoded_13  encoded_15  encoded_17   encoded_19  ...   encoded_71  \
0      0.00000     0.00000     0.00000     0.000000  ...     0.000000   
1      0.00000     0.00000     0.00000     0.000000  ...     0.000000   
2      0.00000     0.00000     0.00000     0.000000  ...     0.000000   
3      0.00000     0.00000   313.12375     0.000000  ...   298.376560   
4    534.24140     0.00000     0.00000    63.631020  ...     0.000000   
5      0.00000     0.00000     0.00000   725.103940  ...     0.000000   
6    492.86234   302.24435   271.91568     0.000000  ...   261.661830   
7      0.00000  2132.31670  1004.79240  1368.450300  ...     0.000000   
8      0.00000     0.00000     0.00000     0.000000  ...     0.000000   
9    407.91858     0.00000   114.94674    30.607542  ...   118.383125   
10     0.00000     0.00000     0.00000     0.000000  ...     0.000000   
11     0.00000     0.00000   471.74078     0.000000  ...     0.000000   
12     0.00000     0.00000     0.00000     0.000000  ...  1204.033100   
13     0.00000     0.00000     0.00000    70.021220  ...   176.984650   
14   523.96980   208.60474   130.86180     0.000000  ...   244.482160   
15     0.00000     0.00000     0.00000   203.095280  ...    84.314964   
16     0.00000     0.00000     0.00000     0.000000  ...     0.000000   
17     0.00000     0.00000     0.00000     0.000000  ...     0.000000   
18     0.00000     0.00000     0.00000     0.000000  ...     0.000000   
19     0.00000     0.00000     0.00000     0.000000  ...     0.000000   
20     0.00000     0.00000     0.00000     0.000000  ...     0.000000   

    encoded_72   encoded_78  encoded_80  encoded_81   encoded_84   encoded_88  \
0      0.00000     0.000000     0.00000    0.000000     0.000000     0.000000   
1      0.00000     0.000000  1892.34020    0.000000     0.000000     0.000000   
2      0.00000  1928.657000     0.00000    0.000000     0.000000   514.910400   
3      0.00000    23.500320     0.00000  114.356995    10.897052    20.788239   
4      0.00000     0.000000   279.44452  145.552670     0.000000     0.000000   
5    724.23830     0.000000     0.00000    0.000000     0.000000     0.000000   
6      0.00000    91.773460     0.00000    0.000000     0.000000     0.000000   
7      0.000

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, VotingClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
data = pd.read_csv("optimized_dataset2.csv")

# Step 2: Data preprocessing
# Separate features and target
X = data.drop(columns=["Label"])  # Features
y = data["Label"]  # Target

# Encode the target labels ("cancerous" -> 0, "healthy" -> 1)
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # Converts "cancerous" to 0 and "healthy" to 1

# Check label mapping (optional)
print(f"Label Mapping: {dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))}")

# Scale the feature values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Step 3: Initialize classifiers
logistic_clf = LogisticRegression(random_state=42, max_iter=1000)
svm_clf = SVC(kernel="linear", probability=True, random_state=42)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
knn_clf = KNeighborsClassifier(n_neighbors=5)
gb_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)
hist_gb_clf = HistGradientBoostingClassifier(random_state=42)  # scikit-learn's version of gradient boosting
ada_clf = AdaBoostClassifier(n_estimators=100, random_state=42)

# Step 4: Combine classifiers into a Voting Classifier
voting_clf = VotingClassifier(
    estimators=[
        ("log_reg", logistic_clf),
        ("svm", svm_clf),
        ("rf", rf_clf),
        ("knn", knn_clf),
        ("gb", gb_clf),
        ("hist_gb", hist_gb_clf),
        ("ada", ada_clf)
    ],
    voting="soft"  # Soft voting uses predicted probabilities
)

# Step 5: Train the Voting Classifier
voting_clf.fit(X_train, y_train)

# Step 6: Make predictions and evaluate the model
voting_predictions = voting_clf.predict(X_test)
voting_accuracy = accuracy_score(y_test, voting_predictions)

print("\n--- Voting Classifier ---")
print(f"Accuracy: {voting_accuracy:.4f}")

# Detailed evaluation
print("\n--- Classification Report ---")
print(classification_report(y_test, voting_predictions, target_names=["cancerous", "healthy"]))

# Confusion matrix
print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, voting_predictions))


Label Mapping: {'cancerous': 0, 'healthy': 1}

--- Voting Classifier ---
Accuracy: 0.6000

--- Classification Report ---
              precision    recall  f1-score   support

   cancerous       0.67      0.67      0.67         3
     healthy       0.50      0.50      0.50         2

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5


--- Confusion Matrix ---
[[2 1]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, HistGradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define base estimators
logistic_clf = LogisticRegression(max_iter=1000)
svm_clf = SVC(probability=True)  # Bagging requires probability=True for some metrics
rf_clf = RandomForestClassifier()
knn_clf = KNeighborsClassifier()
gb_clf = GradientBoostingClassifier()
hgb_clf = HistGradientBoostingClassifier()
ada_clf = AdaBoostClassifier()

# Step 4: Define Bagging Classifiers for each algorithm
bagging_logistic = BaggingClassifier(estimator=logistic_clf, n_estimators=10, random_state=42)
bagging_svm = BaggingClassifier(estimator=svm_clf, n_estimators=10, random_state=42)
bagging_rf = BaggingClassifier(estimator=rf_clf, n_estimators=10, random_state=42)
bagging_knn = BaggingClassifier(estimator=knn_clf, n_estimators=10, random_state=42)
bagging_gb = BaggingClassifier(estimator=gb_clf, n_estimators=10, random_state=42)
bagging_hgb = BaggingClassifier(estimator=hgb_clf, n_estimators=10, random_state=42)
bagging_ada = BaggingClassifier(estimator=ada_clf, n_estimators=10, random_state=42)

# Step 5: Train and evaluate each Bagging Classifier
bagging_classifiers = {
    "Bagging_Logistic": bagging_logistic,
    "Bagging_SVM": bagging_svm,
    "Bagging_RandomForest": bagging_rf,
    "Bagging_KNN": bagging_knn,
    "Bagging_GradientBoosting": bagging_gb,
    "Bagging_HistGradientBoosting": bagging_hgb,
    "Bagging_AdaBoost": bagging_ada,
}

accuracies = []

for name, clf in bagging_classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

    print(f"\n--- {name} ---")
    print("Accuracy:", accuracy)
    print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Step 6: Calculate the average accuracy
final_accuracy = np.mean(accuracies)
print(f"\nFinal Average Accuracy: {final_accuracy}")


Label Mapping: {'cancerous': 0, 'healthy': 1}

--- Bagging_Logistic ---
Accuracy: 0.4

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.00      0.00      0.00         3
     healthy       0.40      1.00      0.57         2

    accuracy                           0.40         5
   macro avg       0.20      0.50      0.29         5
weighted avg       0.16      0.40      0.23         5


Confusion Matrix:
 [[0 3]
 [0 2]]

--- Bagging_SVM ---
Accuracy: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



--- Bagging_RandomForest ---
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      1.00      1.00         3
     healthy       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5


Confusion Matrix:
 [[3 0]
 [0 2]]

--- Bagging_KNN ---
Accuracy: 0.4

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.00      0.00      0.00         3
     healthy       0.40      1.00      0.57         2

    accuracy                           0.40         5
   macro avg       0.20      0.50      0.29         5
weighted avg       0.16      0.40      0.23         5


Confusion Matrix:
 [[0 3]
 [0 2]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



--- Bagging_GradientBoosting ---
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      1.00      1.00         3
     healthy       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5


Confusion Matrix:
 [[3 0]
 [0 2]]

--- Bagging_HistGradientBoosting ---
Accuracy: 0.6

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.60      1.00      0.75         3
     healthy       0.00      0.00      0.00         2

    accuracy                           0.60         5
   macro avg       0.30      0.50      0.38         5
weighted avg       0.36      0.60      0.45         5


Confusion Matrix:
 [[3 0]
 [2 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/e


--- Bagging_AdaBoost ---
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      1.00      1.00         3
     healthy       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5


Confusion Matrix:
 [[3 0]
 [0 2]]

Final Average Accuracy: 0.7428571428571429


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:605: RuntimeWarning: divide by zero encountered in log
  np.log(sample_weight)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define boosting classifiers
boosting_logistic = GradientBoostingClassifier(n_estimators=50, random_state=42)
boosting_svm = GradientBoostingClassifier(n_estimators=50, random_state=42)
boosting_rf = GradientBoostingClassifier(n_estimators=50, random_state=42)
boosting_knn = GradientBoostingClassifier(n_estimators=50, random_state=42)
boosting_gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
boosting_hgb = HistGradientBoostingClassifier(max_iter=100, random_state=42)
boosting_ada = AdaBoostClassifier(n_estimators=50, random_state=42)

# Step 4: Define the classifiers in a dictionary
boosting_classifiers = {
    "Boosting_Logistic": boosting_logistic,
    "Boosting_SVM": boosting_svm,
    "Boosting_RandomForest": boosting_rf,
    "Boosting_KNN": boosting_knn,
    "Boosting_GradientBoosting": boosting_gb,
    "Boosting_HistGradientBoosting": boosting_hgb,
    "Boosting_AdaBoost": boosting_ada,
}

accuracies = []

# Step 5: Train and evaluate each boosting classifier
for name, clf in boosting_classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

    print(f"\n--- {name} ---")
    print("Accuracy:", accuracy)
    print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Step 6: Calculate the average accuracy
final_accuracy = np.mean(accuracies)
print(f"\nFinal Average Accuracy: {final_accuracy}")


Label Mapping: {'cancerous': 0, 'healthy': 1}

--- Boosting_Logistic ---
Accuracy: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]

--- Boosting_SVM ---
Accuracy: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]

--- Boosting_RandomForest ---
Accuracy: 0.8

Classification Report:
               precision    recall

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define base learners
base_learners = [
    ("logistic", LogisticRegression(max_iter=1000, random_state=42)),
    ("rf", RandomForestClassifier(random_state=42)),
    ("svm", SVC(probability=True, random_state=42)),
    ("knn", KNeighborsClassifier()),
    ("gb", GradientBoostingClassifier(n_estimators=50, random_state=42)),
    ("ada", AdaBoostClassifier(n_estimators=50, random_state=42)),
]

# Step 4: Define the meta-classifier
meta_classifier = LogisticRegression(max_iter=1000, random_state=42)

# Step 5: Define the StackingClassifier
stacking_clf = StackingClassifier(estimators=base_learners, final_estimator=meta_classifier, cv=5)

# Step 6: Train and evaluate the StackingClassifier
stacking_clf.fit(X_train, y_train)
y_pred = stacking_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy of Stacking Classifier: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))



Label Mapping: {'cancerous': 0, 'healthy': 1}
Accuracy of Stacking Classifier: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define base learners with hyperparameters for GridSearchCV
param_grid_lr = {'C': [0.01, 0.1, 1, 10], 'max_iter': [1000]}
param_grid_rf = {'n_estimators': [50, 100, 200], 'max_depth': [10, 20, None], 'min_samples_split': [2, 5]}
param_grid_svm = {'C': [0.01, 0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}
param_grid_knn = {'n_neighbors': [3, 5, 7], 'weights': ['uniform', 'distance']}
param_grid_gb = {'n_estimators': [50, 100], 'learning_rate': [0.01, 0.1, 1], 'max_depth': [3, 5]}
param_grid_ada = {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.1, 1]}

# Step 4: Create base learners with GridSearchCV
lr_clf = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42), param_grid_lr, cv=5)
rf_clf = GridSearchCV(RandomForestClassifier(random_state=42), param_grid_rf, cv=5)
svm_clf = GridSearchCV(SVC(probability=True, random_state=42), param_grid_svm, cv=5)
knn_clf = GridSearchCV(KNeighborsClassifier(), param_grid_knn, cv=5)
gb_clf = GridSearchCV(GradientBoostingClassifier(random_state=42), param_grid_gb, cv=5)
ada_clf = GridSearchCV(AdaBoostClassifier(random_state=42), param_grid_ada, cv=5)

# Step 5: Define the meta-classifier and tune hyperparameters
param_grid_meta = {'C': [0.01, 0.1, 1, 10], 'max_iter': [1000]}
meta_classifier = GridSearchCV(LogisticRegression(max_iter=1000, random_state=42), param_grid_meta, cv=5)

# Step 6: Define the StackingClassifier with hyperparameter-tuned base learners and meta-classifier
stacking_clf = StackingClassifier(
    estimators=[("logistic", lr_clf), ("rf", rf_clf), ("svm", svm_clf), ("knn", knn_clf), ("gb", gb_clf), ("ada", ada_clf)],
    final_estimator=meta_classifier,
    cv=5
)

# Step 7: Train and evaluate the StackingClassifier
stacking_clf.fit(X_train, y_train)
y_pred = stacking_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy of Stacking Classifier: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))



Label Mapping: {'cancerous': 0, 'healthy': 1}


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklea

Accuracy of Stacking Classifier: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from scipy.stats import randint, uniform

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define base learners with hyperparameters for RandomizedSearchCV
# Random Forest parameters
param_dist_rf = {
    'n_estimators': randint(50, 300),
    'max_depth': [10, 20, None],
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}
rf_clf = RandomizedSearchCV(RandomForestClassifier(random_state=42), param_distributions=param_dist_rf, n_iter=20, cv=2, random_state=42)

# SVM parameters
param_dist_svm = {
    'C': uniform(0.01, 10),
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto']
}
svm_clf = RandomizedSearchCV(SVC(probability=True, random_state=42), param_distributions=param_dist_svm, n_iter=20, cv=2, random_state=42)

# KNN parameters
param_dist_knn = {
    'n_neighbors': randint(3, 20),
    'weights': ['uniform', 'distance'],
    'p': [1, 2]  # Manhattan or Euclidean distance
}
knn_clf = RandomizedSearchCV(KNeighborsClassifier(), param_distributions=param_dist_knn, n_iter=20, cv=2, random_state=42)

# Gradient Boosting parameters
param_dist_gb = {
    'n_estimators': randint(50, 200),
    'learning_rate': uniform(0.01, 0.5),
    'max_depth': randint(3, 10)
}
gb_clf = RandomizedSearchCV(GradientBoostingClassifier(random_state=42), param_distributions=param_dist_gb, n_iter=20, cv=2, random_state=42)

# AdaBoost parameters
param_dist_ada = {
    'n_estimators': randint(50, 200),
    'learning_rate': uniform(0.01, 0.5)
}
ada_clf = RandomizedSearchCV(AdaBoostClassifier(random_state=42), param_distributions=param_dist_ada, n_iter=20, cv=2, random_state=42)

# Logistic Regression parameters (meta-classifier)
param_dist_meta = {
    'C': uniform(0.01, 10),
    'max_iter': [500, 1000, 2000]
}
meta_classifier = RandomizedSearchCV(LogisticRegression(max_iter=1000, random_state=42), param_distributions=param_dist_meta, n_iter=20, cv=2, random_state=42)

# Step 4: Define the StackingClassifier
stacking_clf = StackingClassifier(
    estimators=[
        ("rf", rf_clf),
        ("svm", svm_clf),
        ("knn", knn_clf),
        ("gb", gb_clf),
        ("ada", ada_clf)
    ],
    final_estimator=meta_classifier,
    cv=2
)

# Step 5: Train and evaluate the StackingClassifier
print("Training Stacking Classifier...")
stacking_clf.fit(X_train, y_train)

# Predictions
y_pred = stacking_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

# Step 6: Display results
print(f"\nAccuracy of Stacking Classifier: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Label Mapping: {'cancerous': 0, 'healthy': 1}
Training Stacking Classifier...


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 472, in __call__
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 572, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py", line 262, in predict
    probabilities = self.pr


Accuracy of Stacking Classifier: 0.8000

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from scipy.stats import randint, uniform

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define hyperparameter search spaces
# Random Forest parameters
param_dist_rf = {
    'n_estimators': randint(50, 300),
    'max_depth': [10, 20, None],
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}

# SVM parameters
param_dist_svm = {
    'C': uniform(0.1, 10),
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto']
}

# KNN parameters
param_dist_knn = {
    'n_neighbors': randint(3, 20),
    'weights': ['uniform', 'distance'],
    'p': [1, 2]  # Manhattan or Euclidean distance
}

# Gradient Boosting parameters
param_dist_gb = {
    'n_estimators': randint(50, 200),
    'learning_rate': uniform(0.01, 0.5),
    'max_depth': randint(3, 10)
}

# AdaBoost parameters
param_dist_ada = {
    'n_estimators': randint(50, 200),
    'learning_rate': uniform(0.01, 0.5)
}

# Meta-classifier parameters
param_dist_meta = {
    'C': uniform(0.1, 10),
    'max_iter': [500, 1000, 2000]
}

# Step 4: Perform hyperparameter tuning using RandomizedSearchCV
print("Tuning base learners...")

# Random Forest
rf_clf = RandomizedSearchCV(RandomForestClassifier(random_state=42), param_dist_rf, n_iter=20, cv=3, random_state=42)
rf_clf.fit(X_train, y_train)
print("Best parameters for Random Forest:", rf_clf.best_params_)

# SVM
svm_clf = RandomizedSearchCV(SVC(probability=True, random_state=42), param_dist_svm, n_iter=20, cv=3, random_state=42)
svm_clf.fit(X_train, y_train)
print("Best parameters for SVM:", svm_clf.best_params_)

# KNN
knn_clf = RandomizedSearchCV(KNeighborsClassifier(), param_dist_knn, n_iter=20, cv=3, random_state=42)
knn_clf.fit(X_train, y_train)
print("Best parameters for KNN:", knn_clf.best_params_)

# Gradient Boosting
gb_clf = RandomizedSearchCV(GradientBoostingClassifier(random_state=42), param_dist_gb, n_iter=20, cv=3, random_state=42)
gb_clf.fit(X_train, y_train)
print("Best parameters for Gradient Boosting:", gb_clf.best_params_)

# AdaBoost
ada_clf = RandomizedSearchCV(AdaBoostClassifier(random_state=42), param_dist_ada, n_iter=20, cv=3, random_state=42)
ada_clf.fit(X_train, y_train)
print("Best parameters for AdaBoost:", ada_clf.best_params_)

# Meta-classifier
meta_clf = RandomizedSearchCV(LogisticRegression(random_state=42), param_dist_meta, n_iter=20, cv=3, random_state=42)
meta_clf.fit(X_train, y_train)
print("Best parameters for Meta-classifier:", meta_clf.best_params_)

# Step 5: Build the StackingClassifier with tuned parameters
print("Building the stacking classifier...")

base_learners = [
    ("rf", rf_clf.best_estimator_),
    ("svm", svm_clf.best_estimator_),
    ("knn", knn_clf.best_estimator_),
    ("gb", gb_clf.best_estimator_),
    ("ada", ada_clf.best_estimator_),
]

stacking_clf = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_clf.best_estimator_,
    cv=5
)

# Step 6: Train the StackingClassifier
stacking_clf.fit(X_train, y_train)

# Step 7: Evaluate the StackingClassifier
y_pred = stacking_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy of Tuned Stacking Classifier: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Tuning base learners...
Best parameters for Random Forest: {'max_depth': 10, 'min_samples_leaf': 3, 'min_samples_split': 4, 'n_estimators': 219}
Best parameters for SVM: {'C': 8.424426408004217, 'gamma': 'auto', 'kernel': 'rbf'}


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 472, in __call__
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py", line 446, in score
    return super().score(X, y, sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 572, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py", line 277, in predict
    neigh_dist, neigh_ind =

Best parameters for KNN: {'n_neighbors': 9, 'p': 2, 'weights': 'distance'}
Best parameters for Gradient Boosting: {'learning_rate': 0.19727005942368125, 'max_depth': 7, 'n_estimators': 64}
Best parameters for AdaBoost: {'learning_rate': 0.10171739493308189, 'n_estimators': 121}
Best parameters for Meta-classifier: {'C': 3.845401188473625, 'max_iter': 500}
Building the stacking classifier...
Accuracy of Tuned Stacking Classifier: 0.8000

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Step 4: Define base learners
base_learners = [
    ("logistic", LogisticRegression(max_iter=1000, random_state=42)),
    ("rf", RandomForestClassifier(random_state=42)),
    ("svm", SVC(probability=True, random_state=42)),
    ("knn", KNeighborsClassifier()),
    ("gb", GradientBoostingClassifier(n_estimators=50, random_state=42)),
    ("ada", AdaBoostClassifier(n_estimators=50, random_state=42)),
]

# Step 5: Define the meta-classifier
meta_classifier = LogisticRegression(max_iter=1000, random_state=42)

# Step 6: Define the StackingClassifier
stacking_clf = StackingClassifier(estimators=base_learners, final_estimator=meta_classifier, cv=5)

# Step 7: Hyperparameter tuning (optional, can be skipped)
# Define hyperparameter grid
param_grid = {
    "rf__n_estimators": [50, 100, 200],
    "gb__n_estimators": [50, 100, 200],
    "ada__n_estimators": [50, 100, 200],
    "knn__n_neighbors": [3, 5, 7],
    "svm__C": [0.1, 1, 10],
}

grid_search = GridSearchCV(estimator=stacking_clf, param_grid=param_grid, cv=3, scoring="accuracy", n_jobs=-1)
grid_search.fit(X_resampled, y_resampled)

# Use the best estimator from GridSearchCV
best_model = grid_search.best_estimator_

# Step 8: Train and evaluate the final StackingClassifier
best_model.fit(X_resampled, y_resampled)
y_pred = best_model.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy of Tuned Stacking Classifier with SMOTE: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Label Mapping: {'cancerous': 0, 'healthy': 1}


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


Accuracy of Tuned Stacking Classifier with SMOTE: 0.8

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.75      1.00      0.86         3
     healthy       1.00      0.50      0.67         2

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5


Confusion Matrix:
 [[3 0]
 [1 1]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Step 3: Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)
print(f"Class distribution after SMOTE: {np.bincount(y)}")

# Step 4: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Define the BaggingClassifier
base_estimator = DecisionTreeClassifier(random_state=42)
bagging_clf = BaggingClassifier(estimator=base_estimator, random_state=42)

# Step 6: Define hyperparameter grid for tuning
param_grid = {
    "n_estimators": [10, 20, 50],          # Number of base estimators
    "max_samples": [0.5, 0.7, 1.0],       # Max samples for each base estimator
    "max_features": [0.5, 0.7, 1.0],      # Max features for each base estimator
    "bootstrap": [True, False],           # Whether to bootstrap samples
    "bootstrap_features": [True, False]   # Whether to bootstrap features
}

# Step 7: Perform hyperparameter tuning using GridSearchCV
grid_search = GridSearchCV(estimator=bagging_clf, param_grid=param_grid, cv=5, scoring="accuracy", n_jobs=-1)
grid_search.fit(X_train, y_train)

# Step 8: Evaluate the best model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\n--- Best Hyperparameters ---")
print(grid_search.best_params_)

print("\n--- Evaluation on Test Data ---")
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Step 9: Save average accuracy of cross-validation
cv_results = grid_search.cv_results_
mean_accuracy = np.max(cv_results["mean_test_score"])
print(f"\nBest Cross-Validation Accuracy: {mean_accuracy}")


Label Mapping: {'cancerous': 0, 'healthy': 1}
Class distribution after SMOTE: [13 13]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(



--- Best Hyperparameters ---
{'bootstrap': True, 'bootstrap_features': True, 'max_features': 0.5, 'max_samples': 0.7, 'n_estimators': 20}

--- Evaluation on Test Data ---
Accuracy: 0.8333333333333334

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      0.75      0.86         4
     healthy       0.67      1.00      0.80         2

    accuracy                           0.83         6
   macro avg       0.83      0.88      0.83         6
weighted avg       0.89      0.83      0.84         6


Confusion Matrix:
 [[3 1]
 [0 2]]

Best Cross-Validation Accuracy: 0.85


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Define the GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(random_state=42)

# Step 4: Define the hyperparameter grid for GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'min_samples_split': [2, 5, 10],
    'subsample': [0.8, 0.9, 1.0],
    'max_features': [0.5, 0.7, 1.0],
}

# Step 5: Perform GridSearchCV to tune hyperparameters
grid_search = GridSearchCV(estimator=gb_clf, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Step 6: Get the best hyperparameters from the grid search
print("\n--- Best Hyperparameters ---")
print(grid_search.best_params_)

# Step 7: Evaluate the model on test data with the best hyperparameters
best_gb_clf = grid_search.best_estimator_

# Predict and evaluate
y_pred = best_gb_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("\n--- Evaluation on Test Data ---")
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Label Mapping: {'cancerous': 0, 'healthy': 1}
Fitting 5 folds for each of 729 candidates, totalling 3645 fits

--- Best Hyperparameters ---
{'learning_rate': 0.01, 'max_depth': 3, 'max_features': 0.7, 'min_samples_split': 2, 'n_estimators': 50, 'subsample': 0.8}

--- Evaluation on Test Data ---
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      1.00      1.00         3
     healthy       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5


Confusion Matrix:
 [[3 0]
 [0 2]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Step 3: Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)
print(f"Class distribution after SMOTE: {np.bincount(y)}")

# Step 4: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Define the GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(random_state=42)

# Step 6: Define hyperparameter grid for tuning
param_grid = {
    "n_estimators": [50, 100, 150],              # Number of boosting stages
    "learning_rate": [0.01, 0.05, 0.1],         # Learning rate
    "max_depth": [3, 4, 5],                     # Max depth of individual estimators
    "min_samples_split": [2, 5, 10],            # Minimum samples to split an internal node
    "subsample": [0.7, 0.8, 1.0],               # Fraction of samples used for fitting the base learners
    "max_features": [0.5, 0.7, 1.0],            # Fraction of features used for fitting each base learner
}

# Step 7: Perform hyperparameter tuning using GridSearchCV
grid_search = GridSearchCV(estimator=gb_clf, param_grid=param_grid, cv=5, scoring="accuracy", n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Step 8: Evaluate the best model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\n--- Best Hyperparameters ---")
print(grid_search.best_params_)

print("\n--- Evaluation on Test Data ---")
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Step 9: Save average accuracy of cross-validation
cv_results = grid_search.cv_results_
mean_accuracy = np.max(cv_results["mean_test_score"])
print(f"\nBest Cross-Validation Accuracy: {mean_accuracy}")


Label Mapping: {'cancerous': 0, 'healthy': 1}
Class distribution after SMOTE: [13 13]
Fitting 5 folds for each of 729 candidates, totalling 3645 fits


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(



--- Best Hyperparameters ---
{'learning_rate': 0.1, 'max_depth': 3, 'max_features': 0.7, 'min_samples_split': 10, 'n_estimators': 150, 'subsample': 1.0}

--- Evaluation on Test Data ---
Accuracy: 0.8333333333333334

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      0.75      0.86         4
     healthy       0.67      1.00      0.80         2

    accuracy                           0.83         6
   macro avg       0.83      0.88      0.83         6
weighted avg       0.89      0.83      0.84         6


Confusion Matrix:
 [[3 1]
 [0 2]]

Best Cross-Validation Accuracy: 0.9


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.pipeline import Pipeline
from sklearn.utils.class_weight import compute_class_weight

# Step 1: Load the dataset
df = pd.read_csv("optimized_dataset2.csv")

# Step 2: Preprocess the data
# Separate features and target
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Compute class weights
class_weights = compute_class_weight("balanced", classes=np.unique(y), y=y)
class_weights_dict = dict(zip(np.unique(y), class_weights))
print(f"Class Weights: {class_weights_dict}")

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Step 3: Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)
print(f"Class distribution after SMOTE: {np.bincount(y)}")

# Step 4: Apply PCA for dimensionality reduction
pca = PCA(n_components=0.95)  # Retain 95% variance
X = pca.fit_transform(X)
print(f"Number of PCA components: {pca.n_components_}")

# Step 5: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Define the GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(random_state=42)

# Step 7: Define hyperparameter grid for tuning
param_grid = {
    "n_estimators": [100, 150, 200],           # Number of boosting stages
    "learning_rate": [0.01, 0.05, 0.1, 0.2],  # Learning rate
    "max_depth": [3, 4, 5],                   # Max depth of individual estimators
    "min_samples_split": [2, 5, 10],          # Minimum samples to split an internal node
    "subsample": [0.7, 0.8, 1.0],             # Fraction of samples used for fitting the base learners
    "max_features": [0.5, 0.7, 1.0],          # Fraction of features used for fitting each base learner
}

# Step 8: Perform hyperparameter tuning using GridSearchCV
grid_search = GridSearchCV(
    estimator=gb_clf,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)
grid_search.fit(X_train, y_train)

# Step 9: Evaluate the best Gradient Boosting model
best_gb_model = grid_search.best_estimator_
y_pred_gb = best_gb_model.predict(X_test)

print("\n--- Best Hyperparameters ---")
print(grid_search.best_params_)

print("\n--- Evaluation on Test Data (Gradient Boosting) ---")
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Accuracy:", accuracy_gb)
print("\nClassification Report:\n", classification_report(y_test, y_pred_gb, target_names=label_encoder.classes_))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))

# Step 10: Ensemble Learning with Random Forest
rf_clf = RandomForestClassifier(random_state=42, class_weight=class_weights_dict)
rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)

# Combine predictions using a simple majority voting scheme
ensemble_pred = np.round((y_pred_gb + y_pred_rf) / 2).astype(int)
ensemble_accuracy = accuracy_score(y_test, ensemble_pred)

print("\n--- Ensemble Model Accuracy ---")
print("Accuracy:", ensemble_accuracy)

# Step 11: Save average accuracy of cross-validation
cv_results = grid_search.cv_results_
mean_accuracy = np.max(cv_results["mean_test_score"])
print(f"\nBest Cross-Validation Accuracy: {mean_accuracy}")


Label Mapping: {'cancerous': 0, 'healthy': 1}
Class Weights: {0: 0.8076923076923077, 1: 1.3125}
Class distribution after SMOTE: [13 13]
Number of PCA components: 13
Fitting 5 folds for each of 972 candidates, totalling 4860 fits


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(



--- Best Hyperparameters ---
{'learning_rate': 0.2, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 10, 'n_estimators': 100, 'subsample': 0.7}

--- Evaluation on Test Data (Gradient Boosting) ---
Gradient Boosting Accuracy: 0.8333333333333334

Classification Report:
               precision    recall  f1-score   support

   cancerous       1.00      0.75      0.86         4
     healthy       0.67      1.00      0.80         2

    accuracy                           0.83         6
   macro avg       0.83      0.88      0.83         6
weighted avg       0.89      0.83      0.84         6


Confusion Matrix:
 [[3 1]
 [0 2]]

--- Ensemble Model Accuracy ---
Accuracy: 0.8333333333333334

Best Cross-Validation Accuracy: 1.0


Label Mapping: {'cancerous': 0, 'healthy': 1}
Class distribution after SMOTE: [13 13]
Fitting 5 folds for each of 4096 candidates, totalling 20480 fits


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(



--- Best Hyperparameters ---
{'learning_rate': 0.01, 'max_depth': 3, 'max_features': 0.7, 'min_samples_split': 2, 'n_estimators': 50, 'subsample': 1.0}

--- Evaluation on Test Data ---
Accuracy: 0.6666666666666666

Classification Report:
               precision    recall  f1-score   support

   cancerous       0.67      0.67      0.67         3
     healthy       0.67      0.67      0.67         3

    accuracy                           0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6


Confusion Matrix:
 [[2 1]
 [1 2]]

Best Cross-Validation Accuracy: 0.9


In [ ]:
!pip install git+https://github.com/scikit-fuzzy/scikit-fuzzy.git


  Cloning https://github.com/scikit-fuzzy/scikit-fuzzy.git to /tmp/pip-req-build-vwm80_mf
  Running command git clone --filter=blob:none --quiet https://github.com/scikit-fuzzy/scikit-fuzzy.git /tmp/pip-req-build-vwm80_mf
  Resolved https://github.com/scikit-fuzzy/scikit-fuzzy.git to commit be7e344f3ce65845e39922aa5fc1af7412d01944
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.5.0-py2.py3-none-any.whl size=920818 sha256=12c32765686bb45110adafa654384c9a100498dda98acf4431f72f1ab0846fda
  Stored in directory: /tmp/pip-ephem-wheel-cache-ucucdx1d/wheels/5c/84/31/a14f5979df363e74a35e1bf98d4455f7abfa8f0da6c4474afe
Successfully built scikit-fuzzy


In [ ]:
!pip install anfis


In [ ]:
!pip uninstall anfis -y


Found existing installation: anfis 0.3.1
Uninstalling anfis-0.3.1:
  Successfully uninstalled anfis-0.3.1


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Load and preprocess the dataset
df = pd.read_csv("optimized_dataset2.csv")
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define fuzzy variables
feature1 = ctrl.Antecedent(np.arange(0, 11, 1), 'Feature1')
feature2 = ctrl.Antecedent(np.arange(0, 11, 1), 'Feature2')
output = ctrl.Consequent(np.arange(0, 3, 1), 'Output')  # Assume 3 classes (0, 1, 2)

# Define fuzzy membership functions for input features
feature1['low'] = fuzz.trimf(feature1.universe, [0, 0, 5])
feature1['high'] = fuzz.trimf(feature1.universe, [5, 10, 10])
feature2['low'] = fuzz.trimf(feature2.universe, [0, 0, 5])
feature2['high'] = fuzz.trimf(feature2.universe, [5, 10, 10])

# Define fuzzy membership functions for output
output['class0'] = fuzz.trimf(output.universe, [0, 0, 1])
output['class1'] = fuzz.trimf(output.universe, [0, 1, 2])
output['class2'] = fuzz.trimf(output.universe, [1, 2, 2])

# Define fuzzy rules
rule1 = ctrl.Rule(feature1['low'] & feature2['low'], output['class0'])
rule2 = ctrl.Rule(feature1['high'] & feature2['low'], output['class1'])
rule3 = ctrl.Rule(feature1['low'] & feature2['high'], output['class2'])

# Create fuzzy control system
fuzzy_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
fuzzy_model = ctrl.ControlSystemSimulation(fuzzy_ctrl)

# Now you can make predictions on test data
y_pred = []
for i in range(len(X_test)):
    # Set inputs for the fuzzy model
    fuzzy_model.input['Feature1'] = X_test[i, 0]
    fuzzy_model.input['Feature2'] = X_test[i, 1]

    # Perform fuzzy inference
    fuzzy_model.compute()

    # Get the output and store the predicted class
    predicted_class = fuzzy_model.output['Output']
    y_pred.append(predicted_class)

# Convert predictions to nearest integer class
y_pred = np.round(np.array(y_pred)).astype(int)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.6

Classification Report:
               precision    recall  f1-score   support

           0       0.60      1.00      0.75         3
           1       0.00      0.00      0.00         2

    accuracy                           0.60         5
   macro avg       0.30      0.50      0.38         5
weighted avg       0.36      0.60      0.45         5


Confusion Matrix:
 [[3 0]
 [2 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import skfuzzy as fuzz
from skfuzzy import control as ctrl
from imblearn.over_sampling import SMOTE  # For handling class imbalance

# Load and preprocess the dataset
df = pd.read_csv("optimized_dataset2.csv")
X = df.drop(columns=["Label"])
y = df["Label"]

# Encode target labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Handle class imbalance using SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

# --- Fuzzy Logic Model ---
# Define fuzzy variables
feature1 = ctrl.Antecedent(np.arange(0, 11, 1), 'Feature1')
feature2 = ctrl.Antecedent(np.arange(0, 11, 1), 'Feature2')
output = ctrl.Consequent(np.arange(0, 3, 1), 'Output')  # Assume 3 classes (0, 1, 2)

# Define fuzzy membership functions for input features
feature1['low'] = fuzz.trimf(feature1.universe, [0, 0, 5])
feature1['medium'] = fuzz.trimf(feature1.universe, [0, 5, 10])  # Added medium range
feature1['high'] = fuzz.trimf(feature1.universe, [5, 10, 10])
feature2['low'] = fuzz.trimf(feature2.universe, [0, 0, 5])
feature2['medium'] = fuzz.trimf(feature2.universe, [0, 5, 10])  # Added medium range
feature2['high'] = fuzz.trimf(feature2.universe, [5, 10, 10])

# Define fuzzy membership functions for output
output['class0'] = fuzz.trimf(output.universe, [0, 0, 1])
output['class1'] = fuzz.trimf(output.universe, [0, 1, 2])
output['class2'] = fuzz.trimf(output.universe, [1, 2, 2])

# Define fuzzy rules
rule1 = ctrl.Rule(feature1['low'] & feature2['low'], output['class0'])
rule2 = ctrl.Rule(feature1['medium'] & feature2['low'], output['class1'])  # Added more rules
rule3 = ctrl.Rule(feature1['high'] & feature2['low'], output['class2'])
rule4 = ctrl.Rule(feature1['low'] & feature2['medium'], output['class1'])
rule5 = ctrl.Rule(feature1['high'] & feature2['high'], output['class2'])  # Added more rules

# Create fuzzy control system
fuzzy_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5])
fuzzy_model = ctrl.ControlSystemSimulation(fuzzy_ctrl)

# --- Random Forest Model ---
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# --- Combined Model ---
y_pred_fuzzy = []
for i in range(len(X_test)):
    fuzzy_model.input['Feature1'] = X_test[i, 0]
    fuzzy_model.input['Feature2'] = X_test[i, 1]
    fuzzy_model.compute()
    predicted_class = fuzzy_model.output['Output']
    y_pred_fuzzy.append(predicted_class)

# Convert fuzzy predictions to nearest integer class
y_pred_fuzzy = np.round(np.array(y_pred_fuzzy)).astype(int)

# Random Forest predictions
y_pred_rf = rf_model.predict(X_test)

# Combine fuzzy and random forest predictions (Majority Voting)
combined_pred = []
for i in range(len(y_pred_fuzzy)):
    if y_pred_fuzzy[i] == y_pred_rf[i]:
        combined_pred.append(y_pred_fuzzy[i])
    else:
        # Choose the Random Forest prediction in case of a disagreement
        combined_pred.append(y_pred_rf[i])

# Evaluate the models
print("Fuzzy Model Accuracy:", accuracy_score(y_test, y_pred_fuzzy))
print("\nFuzzy Model Classification Report:\n", classification_report(y_test, y_pred_fuzzy))
print("\nFuzzy Model Confusion Matrix:\n", confusion_matrix(y_test, y_pred_fuzzy))

print("\nRandom Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nRandom Forest Classification Report:\n", classification_report(y_test, y_pred_rf))
print("\nRandom Forest Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

print("\nCombined Model Accuracy:", accuracy_score(y_test, combined_pred))
print("\nCombined Model Classification Report:\n", classification_report(y_test, combined_pred))
print("\nCombined Model Confusion Matrix:\n", confusion_matrix(y_test, combined_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


Fuzzy Model Accuracy: 0.5

Fuzzy Model Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.00      0.00      0.00         2

    accuracy                           0.50         6
   macro avg       0.30      0.38      0.33         6
weighted avg       0.40      0.50      0.44         6


Fuzzy Model Confusion Matrix:
 [[3 1]
 [2 0]]

Random Forest Accuracy: 0.8333333333333334

Random Forest Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.67      1.00      0.80         2

    accuracy                           0.83         6
   macro avg       0.83      0.88      0.83         6
weighted avg       0.89      0.83      0.84         6


Random Forest Confusion Matrix:
 [[3 1]
 [0 2]]

Combined Model Accuracy: 0.8333333333333334

Combined Model Classification Report:
               preci